// Code generated by MockGen. DO NOT EDIT.
// Source: app/open_weather/client.go

// Package mock_openweather is a generated GoMock package.
package mock_openweather

import (
	reflect "reflect"
	models "weathersvc/app/models"

	gomock "github.com/golang/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// ApiTest mocks base method.
func (m *MockClient) ApiTest() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApiTest")
	ret0, _ := ret[0].(error)
	return ret0
}

// ApiTest indicates an expected call of ApiTest.
func (mr *MockClientMockRecorder) ApiTest() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApiTest", reflect.TypeOf((*MockClient)(nil).ApiTest))
}

// GetWeather mocks base method.
func (m *MockClient) GetWeather(lat, lon string) (*models.WeatherResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWeather", lat, lon)
	ret0, _ := ret[0].(*models.WeatherResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWeather indicates an expected call of GetWeather.
func (mr *MockClientMockRecorder) GetWeather(lat, lon interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWeather", reflect.TypeOf((*MockClient)(nil).GetWeather), lat, lon)
}
