version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:8001"
    environment:
      - ENV=${ENV}
      - PORT=${PORT}
      - WEATHER_HOST=${WEATHER_HOST}
      - WEATHER_ID=${WEATHER_ID}
      - SERVICE_URL=${SERVICE_URL}