definitions:
  server.Response:
    properties:
      condition:
        type: string
      message:
        type: string
      temp:
        type: string
      wind:
        type: string
    type: object
info:
  contact: {}
paths:
  /weather/get:
    get:
      description: Get the local weather condition by entering your latitude/longitude
        coordinates.
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/server.Response'
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "429":
          description: Too Many Requests
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Local Weather Condition
swagger: "2.0"
